apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - applications/00-metallb.yaml
  - applications/01-dns.yaml
  - applications/02-ingress-nginx.yaml
  - applications/03-cert-manager.yaml
  - applications/04-nfs-csi.yaml
  - applications/05-platform-certificates.yaml
  - applications/05-argocd-access.yaml
  - applications/06-openbao.yaml
  - applications/07-external-secrets.yaml
  - applications/08-harbor.yaml
  - applications/09-gateway-api.yaml
  - applications/10-kgateway-crds.yaml
  - applications/11-kgateway.yaml
  - applications/12-thunder-secrets.yaml
