apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thunder-database-pvc
  namespace: thunder
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-thunder
  resources:
    requests:
      storage: 2Gi
