apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-resource-type-postgresql.yaml
  - cluster-resource-type-minio.yaml
  - cluster-resource-type-rabbitmq.yaml
  - cluster-resource-type-milvus.yaml
  - cluster-resource-type-redis.yaml
  - environment-development.yaml
  - environment-staging.yaml
  - environment-production.yaml
  - deployment-pipeline.yaml
  - project.yaml
