apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opensearch-admin-credentials
  namespace: openchoreo-observability-plane
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: opensearch-admin-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: observability
        property: opensearch_username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: observability
        property: opensearch_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: observer-secret
  namespace: openchoreo-observability-plane
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: observer-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: OPENSEARCH_USERNAME
      remoteRef:
        key: observability
        property: opensearch_username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: OPENSEARCH_PASSWORD
      remoteRef:
        key: observability
        property: opensearch_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: UID_RESOLVER_OAUTH_CLIENT_SECRET
      remoteRef:
        key: thunder
        property: observer_reader_client_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
