kube-prometheus-stack:
  kube-state-metrics:
    livenessProbe:
      failureThreshold: 12
      timeoutSeconds: 10
  prometheus:
    service:
      type: ClusterIP
    prometheusSpec:
      podMetadata:
        labels:
          openchoreo.dev/system-component: observability-prometheus
      retention: 15d
      retentionSize: 12GB
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 2Gi
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 15Gi
