apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: homelab-platform
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 2.0.1
      helm:
        releaseName: external-secrets
        valuesObject:
          installCRDs: true
          replicaCount: 2
          webhook:
            replicaCount: 2
          certController:
            replicaCount: 2
    - repoURL: https://github.com/YANG18642029437/openchoreo-gitops.git
      targetRevision: main
      path: infrastructure/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
