apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: homelab-platform
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.19.1
      helm:
        releaseName: harbor
        valueFiles:
          - $values/platform/harbor/values.yaml
    - repoURL: https://github.com/YANG18642029437/openchoreo-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  ignoreDifferences:
    - group: ""
      kind: Secret
      namespace: harbor
      jsonPointers:
        - /data
    - group: apps
      kind: Deployment
      namespace: harbor
      jsonPointers:
        - /spec/template/metadata/annotations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
