apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgateway-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: homelab-platform
  source:
    repoURL: cr.kgateway.dev/kgateway-dev/charts
    chart: kgateway-crds
    targetRevision: v2.2.1
    helm:
      releaseName: kgateway-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: openchoreo-control-plane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
