apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thunder
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: homelab-platform
  sources:
    - repoURL: ghcr.io/asgardeo/helm-charts
      chart: thunder
      targetRevision: 0.28.0
      helm:
        releaseName: thunder
        valueFiles:
          - $values/platform/thunder/values.yaml
    - repoURL: https://github.com/YANG18642029437/openchoreo-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/YANG18642029437/openchoreo-gitops.git
      targetRevision: main
      path: platform/thunder-runtime
  destination:
    server: https://kubernetes.default.svc
    namespace: thunder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
