apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openchoreo-observability-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: homelab-platform
  sources:
    - repoURL: ghcr.io/openchoreo/helm-charts
      chart: openchoreo-observability-plane
      targetRevision: 1.1.2
      helm:
        releaseName: openchoreo-observability-plane
        valueFiles:
          - $values/platform/openchoreo/observability-plane-values.yaml
    - repoURL: https://github.com/YANG18642029437/openchoreo-gitops.git
      targetRevision: codex/phase04-gitops
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: openchoreo-observability-plane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
