apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  project: homelab-platform
  source:
    repoURL: https://github.com/YANG18642029437/openchoreo-gitops.git
    targetRevision: codex/phase05-crossplane
    path: platform/apis/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
