---
apiVersion: openchoreo.dev/v1alpha1
kind: ResourceReleaseBinding
metadata:
  name: minio-development
  namespace: agent-platform
spec:
  owner:
    projectName: agent-platform
    resourceName: minio
  environment: development
  retainPolicy: Retain
  resourceRelease: minio-5758654ffc
---
apiVersion: openchoreo.dev/v1alpha1
kind: ResourceReleaseBinding
metadata:
  name: rabbitmq-development
  namespace: agent-platform
spec:
  owner:
    projectName: agent-platform
    resourceName: rabbitmq
  environment: development
  retainPolicy: Retain
  resourceRelease: rabbitmq-5f96bbf5dc
---
apiVersion: openchoreo.dev/v1alpha1
kind: ResourceReleaseBinding
metadata:
  name: milvus-development
  namespace: agent-platform
spec:
  owner:
    projectName: agent-platform
    resourceName: milvus
  environment: development
  retainPolicy: Retain
  resourceRelease: milvus-c84654c84
---
apiVersion: openchoreo.dev/v1alpha1
kind: ResourceReleaseBinding
metadata:
  name: postgresql-development
  namespace: agent-platform
spec:
  owner:
    projectName: agent-platform
    resourceName: postgresql
  environment: development
  retainPolicy: Retain
  resourceRelease: postgresql-d58c5c5cd
---
apiVersion: openchoreo.dev/v1alpha1
kind: ResourceReleaseBinding
metadata:
  name: redis-development
  namespace: agent-platform
spec:
  owner:
    projectName: agent-platform
    resourceName: redis
  environment: development
  retainPolicy: Retain
  resourceRelease: redis-78bc6c7cb
---
apiVersion: openchoreo.dev/v1alpha1
kind: ResourceReleaseBinding
metadata:
  name: clickhouse-development
  namespace: agent-platform
spec:
  owner:
    projectName: agent-platform
    resourceName: clickhouse
  environment: development
  retainPolicy: Retain
  resourceRelease: clickhouse-78f9964f7f
---
apiVersion: openchoreo.dev/v1alpha1
kind: ResourceReleaseBinding
metadata:
  name: langfuse-development
  namespace: agent-platform
spec:
  owner:
    projectName: agent-platform
    resourceName: langfuse
  environment: development
  retainPolicy: Retain
  resourceRelease: langfuse-7449bfdb7d
---
apiVersion: openchoreo.dev/v1alpha1
kind: ResourceReleaseBinding
metadata:
  name: langfuse-retention-development
  namespace: agent-platform
spec:
  owner:
    projectName: agent-platform
    resourceName: langfuse-retention
  environment: development
  retainPolicy: Retain
  resourceRelease: langfuse-retention-5d7498679b
