---
apiVersion: openchoreo.dev/v1alpha1
kind: ResourceReleaseBinding
metadata:
  name: minio-development
  namespace: agent-platform
spec:
  owner:
    projectName: agent-platform
    resourceName: minio
  environment: development
  retainPolicy: Retain
  resourceRelease: minio-5758654ffc
---
apiVersion: openchoreo.dev/v1alpha1
kind: ResourceReleaseBinding
metadata:
  name: rabbitmq-development
  namespace: agent-platform
spec:
  owner:
    projectName: agent-platform
    resourceName: rabbitmq
  environment: development
  retainPolicy: Retain
  resourceRelease: rabbitmq-5f96bbf5dc
---
apiVersion: openchoreo.dev/v1alpha1
kind: ResourceReleaseBinding
metadata:
  name: milvus-development
  namespace: agent-platform
spec:
  owner:
    projectName: agent-platform
    resourceName: milvus
  environment: development
  retainPolicy: Retain
  resourceRelease: milvus-c84654c84
